config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "links#index"

  resources :links
  resources :views, path: :v, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  has_many :views, dependent: :destroy

  scope :recent_first, -> {order(created_at: :desc)}

  validates :url, presence: true

  after_save_commit if: :url_previously_changed? do
    MetadataJob.perform_later(to_param)
  end

  def self.find(id)
    super ShortCode.decode(id)
  end
  def to_param
    ShortCode.encode(id)
  end

  def domain
    URI(url).host rescue URI::InvalidURIError
  end
end

app/models/metadata.rb
require "open-uri"
class Metadata
  attr_reader :doc
  def initialize(html=nil)
    @doc = Nokogiri::HTML(html)
  end

  def self.retrieve_from(url)
    new(URI.open(url))
  rescue StandardError
    new(nil)
  end

  def attributes
    {
      title: title,
      description: description,
      image: image
    }
  end

  def title
    doc.at_css("title")&.text
  end

  def description
    meta_tag_content 'description'
  end

  def image
    meta_tag_content 'og:image', name_attribute: :property
  end

  def meta_tag_content(name, name_attribute: :name)
    doc.at_css("meta[#{name_attribute}='#{name}']")&.attributes&.fetch("content", nil)&.text
  end
end

app/models/short_code.rb
class ShortCode

  ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".freeze
  BASE = ALPHABET.length
  def self.encode(number)
    return ALPHABET.first if number.zero? || number.nil?

    result = ""

    while number > 0 do
      index = number % BASE
      char = ALPHABET[index]
      result.prepend(char)
      number /= BASE
    end

    result
  end

  def self.decode(string)
    number = 0

    string.reverse.each_char.with_index do |char, index|
      power = BASE**index
      index = ALPHABET.index(char)
      number += index * power
    end

    number
  end
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :link, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  def set_link
    @link = Link.find(params[:id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  def index
    @pagy, @links = pagy Link.recent_first
    @link ||= Link.new
  rescue Pagy::OverflowError
    redirect_to root_path
  end

  def create
    @link = Link.new(link_params)

    if @link.save
      respond_to do |format|
        format.html{ redirect_to root_path }
        format.turbo_stream { render turbo_stream: [
          turbo_stream.prepend("links", @link),
          turbo_stream.replace('link_form', partial: 'links/form', locals: {link: Link.new})
        ]}
      end

    else
      index
      render :index, status: :unprocessable_entity
    end
  end

  def show

  end

  def edit

  end

  def update
    if @link.update!(link_params)
      redirect_to @link
    else
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    @link.destroy
    redirect_to root_path, notice: "Link has been deleted"
  end

  private
  def link_params
    params.require(:link).permit(:url)
  end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  before_action :set_link

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to root_path, alert: "Link not found!"
  end

  def show
    @link.views.create(ip: request.ip, user_agent: request.user_agent)
    redirect_to @link.url, allow_other_host: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

end

app/helpers/favicon_helper.rb
module FaviconHelper
  def favicon_image_tag(domain, **kwargs)
    image_tag google_favicon_url(domain), **kwargs
  end

  def google_favicon_url(domain)
    "https://www.google.com/s2/favicons?domain=#{domain}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://unpkg.com/tippy.js@6"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="prose mx-auto mt-28 px-5">
      <% if alert %>
        <p class="bg-yellow-100 text-yellow-800 px-4 py-2 rounded"><%= alert %></p>
      <% end %>

      <% if notice %>
        <p class="bg-green-100 text-green-800 px-4 py-2 rounded"><%= notice %></p>
      <% end %>


      <%= yield %>
    </main>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with model: link, id: 'link_form' do |form| %>
  <div class="flex gap-2 items-center">
    <%= form.url_field :url, placeholder: "https://example.org", class: "flex-grow rounded", required: true, autofocus: true %>
    <%= form.button "Save", class: "px-3 py-2 bg-gray-100 rounded" %>
  </div>
<% end %>

app/views/links/_link.html.erb
<%= tag.div id: dom_id(link) do %>
  <%= turbo_stream_from link %>

  <div class="grid grid-cols-8 items-center py-4">
    <div class="col-span-5">
      <%= link_to view_path(link), target: :_blank, class: "no-underline", data: {turbo: false} do %>
        <%= favicon_image_tag link.domain, class: "inline-block m-0" %>

        <%= link.title || link.url %>
        <%= tag.div link.description, class: "text-xs text-gray-700"%>

        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="inline-block w-4 h-4 ml-1">
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
        </svg>
      <% end %>
    </div>

    <div class="col-span-2 text-center text-xs">
      <%= link_to pluralize(link.views_count, "view"), link, class: "px-3 py-2 bg-gray-100 rounded no-underline" %>
    </div>

    <div class="text-center text-xs">
      <%= button_tag "Copy", data: {controller: "clipboard", clipboard_text: view_url(link)}, class: "font-medium px-3 py-2 bg-gray-100 rounded no-underline" %>
    </div>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Edit Link</h1>

<%= render partial: "form", locals: { link: @link } %>

<div class="flex gap-2 items-center mt-4">
  <%= link_to "Cancel", @link %>
  or
  <%= button_to "Delete", @link, method: :delete, data: { turbo_confirm: "Are you sure ?" } %>
</div>

app/views/links/index.html.erb
<h1>URL Shortener</h1>

<%= render partial: "form", locals: { link: @link } %>


<div id="links" class="mt-8 flex flex-col divide-y divide-gray-100">
  <%= render @links %>

  <div class="pt-8 mb-16 text-center">
      <%== pagy_nav @pagy if @pagy.pages > 1 %>
  </div>

</div>

app/views/links/show.html.erb
<div class="flex flex justify-between items-center text-xs">

  <%= link_to "← Back to all links", root_path, class: "no-underline text-xs px-3 py-2 rounded bg-gray-100" %>

  <div class="flex items-center gap-4">
    <div class="px-2 py-1.5 bg-gray-100 rounded no-underline">
      <%= pluralize(@link.views_count, "view") %>
    </div>

    <%= button_tag "Copy", data: {controller: "clipboard", clipboard_text: view_url(@link)}, class: "font-medium px-3 py-2 bg-gray-100 rounded no-underline" %>

    <%= link_to "Edit", edit_link_path(@link), class: "px-2 py-1.5 bg-gray-100 rounded no-underline" %>
  </div>
</div>

<h1 class="mt-4"><%= @link.url %></h1>
<%= tag.div @link.description %>

<%= link_to view_path(@link), target: :_blank, data: {turbo: false}, class: "text-xs px-2 py-1.5 bg-gray-100 rounded no-underline" do %>
  <%= favicon_image_tag @link.domain, class: "inline-block" %>

  <%= truncate(@link.url) %>

  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="inline-block w-4 h-4 ml-1">
    <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
  </svg>
<% end %>

<%= line_chart @link.views.group_by_day(:created_at, range: 2.weeks.ago..Time.now, expand_range: true).count %>